[versions]
logback = "1.5.21"
logstash = "8.1"
hikari = "7.0.2"
slack = "1.46.0"
postgres = "42.7.8"
jackson = "2.20.1"
junit-jupiter = "6.0.1"
spring-boot = "3.5.8"
spring-doc = "2.8.14"
flyway = "11.17.1"
mockito-kotlin = "6.0.0"

[libraries]

#Spring backend
spring-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-data = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-oauth = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }

#Spring frontend
spring-webclient = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }

#Swagger
swagger = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "spring-doc" }

#flyway
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-db = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

#Logging
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ogstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }


#Postgres
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgressql = { module = "org.postgresql:postgresql", version.ref = "postgres" }

#Jackson
jackson-module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

#Slack
slack-api = { module = "com.slack.api:slack-api-client", version.ref = "slack" }

#reflect
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version = "2.2.21" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.0" }

#jupitor/test
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
spring-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

[bundles]

spring = [
    "spring-boot-data",
    "spring-web",
    "spring-webclient",
    "spring-security",
    "spring-oauth"
]

flyway = [
    "flyway-core",
    "flyway-db"
]

logging = [
    "logback-classic",
    "ogstash"
]

jackson = [
    "jackson-datatype",
    "jackson-module",
    "jackson-core"
]

postgres = [
    "postgressql",
    "hikariCP"
]