[versions]
ktor = "3.3.2"
logback = "2.0.17"
logstash = "8.1"
hikari = "7.0.2"
slack = "1.46.0"
postgres = "42.7.8"
jackson = "2.20.1"
junit-jupiter = "6.0.1"

[libraries]

#Ktor server part
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-natty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor" }
ktor-server-content = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-server-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }

swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }

#Ktor client part
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content = { module = "io.ktor:ktor-client-content-negotiation-jvm", version.ref = "ktor" }

#Logging
slj4-api = { module = "org.slf4j:slf4j-api", version.ref = "logback" }
ogstash = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }


#Postgres
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgressql = { module = "org.postgresql:postgresql", version.ref = "postgres" }

#Jackson
jackson-module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

#Slack
slack-api = { module = "com.slack.api:slack-api-client", version.ref = "slack" }

#jupitor/test
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

[bundles]
ktor-server = [
    "ktor-server-core",
    "ktor-server-natty",
    "ktor-server-auth",
    "ktor-server-content",
    "ktor-server-logging",
    "ktor-server-serialization-kotlinx",
    "ktor-server-cors"
]

ktor-client = [
    "ktor-client-cio",
    "ktor-client-core",
    "ktor-client-content"
]

logging = [
    "slj4-api",
    "ogstash"
]

jackson = [
    "jackson-datatype",
    "jackson-module"
]

postgres = [
    "postgressql",
    "hikariCP"
]