server:
  shutdown: graceful
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /internal
    endpoint:
      security:
        enabled: 'false'
      health:
        show-details: always

spring:
  security:
    token-validation:
      url: ${NAIS_TOKEN_INTROSPECTION_ENDPOINT}
      identity-provider: azuread
      groups: d633d27b-a470-4b9d-984e-85499f126e18
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: ${NAIS_DATABASE_SECURITY_CHAMPION_STATS_BACKEND_SECURITY_CHAMPION_STATS_DB_JDBC_URL}
    username: ${NAIS_DATABASE_SECURITY_CHAMPION_STATS_BACKEND_SECURITY_CHAMPION_STATS_DB_USERNAME}
    password: ${NAIS_DATABASE_SECURITY_CHAMPION_STATS_BACKEND_SECURITY_CHAMPION_STATS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration

slack:
    token: ${SLACK_TOKEN}
    channelId: ${SLACK_CHANNEL_ID}

azure:
  tenantId: ${AZURE_TENANT_ID}
  clientId: ${AZURE_CLIENT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET}

graph:
    apiUrl: https://graph.microsoft.com/v1.0

springdoc:
  api-docs:
    enabled: true

points:
  meetingPoints: ${MEETING_POINTS:10}
  activityPoints: ${ACTIVITY_POINTS:5}