spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  slack:
    token: empty
    channelId: empty

  azure:
    tenantId: empty
    clientId: empty
    clientSecret: empty